blank_issues_enabled: true
contact_links:
  - name: Question / discussion
    url: https://github.com/ilya-pirogov/stateflow/discussions
    about: Ask questions and discuss ideas with the community.
